### ISSUE TITLE
ValueError: Phonemizer is not defined in the TTS config.

### ISSUE THREAD

**Issue by codemmmmm** [thorstenMueller/Thorsten-Voice#38]
Hi,
I was trying to use tts_models/de/thorsten/tacotron2-DCA but I get the error 

> \> tts_models/de/thorsten/tacotron2-DCA is already downloaded.
\> vocoder_models/de/thorsten/fullband-melgan is already downloaded.
Traceback (most recent call last):
  File "/home/user/python/venv/speech/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/home/user/python/venv/speech/lib/python3.10/site-packages/TTS/bin/synthesize.py", line 309, in main
    synthesizer = Synthesizer(
  File "/home/user/python/venv/speech/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 76, in __init__
    self._load_tts(tts_checkpoint, tts_config_path, use_cuda)
  File "/home/user/python/venv/speech/lib/python3.10/site-packages/TTS/utils/synthesizer.py", line 111, in _load_tts
    raise ValueError("Phonemizer is not defined in the TTS config.")
ValueError: Phonemizer is not defined in the TTS config.

The config.json says

>"use_phonemes": true,
    "phonemizer": null,
    "phoneme_language": "de",

which sounds wrong.

**Comment by thorstenMueller** [comment]
You could add `"phonemizer": "espeak",` to config.json.

But it should work with right version (_DCA = 0.5.0 and VITS = 0.7.1_).
You should be able to use DCA model when running `pip install tts==0.5.0` or use newer and better `VITS` model by running `pip install tts==0.7.1` and `tts-server --model_name tts_models/de/thorsten/vits`.

Does this help you?
