### ISSUE TITLE
TTS-Models: Download-Links broken? 

### ISSUE THREAD

**Issue by TaskManager91** [thorstenMueller/Thorsten-Voice#48]
Hi Thorsten - thanks for your effort!

I followed your youtube video, but unfortunately I get an error when I try to download your models.
The direct link unfortunately directs to a Huggingface login window: https://coqui.gateway.scarf.sh/v0.8.0_models/tts_models--de--thorsten--tacotron2-DDC.zip 

```
(tts) D:\Playground\tts>tts --model_name tts_models/de/thorsten/tacotron2-DDC --text "Thorstens TTS ist super" --out_path out.wav
 > Downloading model to C:\Users\Chris\AppData\Local\tts\tts_models--de--thorsten--tacotron2-DDC
  0%|                                                                                                                                               | 0.00/29.0 [00:00<?, ?iB/s] > Error: Bad zip file - https://coqui.gateway.scarf.sh/v0.8.0_models/tts_models--de--thorsten--tacotron2-DDC.zip
Traceback (most recent call last):
  File "D:\Playground\tts\lib\site-packages\TTS\utils\manage.py", line 434, in _download_zip_file
    with zipfile.ZipFile(temp_zip_name) as z:
  File "C:\ProgramData\anaconda3\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\ProgramData\anaconda3\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Playground\tts\Scripts\tts.exe\__main__.py", line 7, in <module>
  File "D:\Playground\tts\lib\site-packages\TTS\bin\synthesize.py", line 345, in main
    model_path, config_path, model_item = manager.download_model(args.model_name)
  File "D:\Playground\tts\lib\site-packages\TTS\utils\manage.py", line 303, in download_model
    self._download_zip_file(model_item["github_rls_url"], output_path, self.progress_bar)
  File "D:\Playground\tts\lib\site-packages\TTS\utils\manage.py", line 439, in _download_zip_file
    raise zipfile.BadZipFile  # pylint: disable=raise-missing-from
zipfile.BadZipFile
```

Could you maybe provide the Tacotron2 model somewhere else? I would like to load it directly via speechbrain anyway e.g.:

```
import torchaudio
from speechbrain.pretrained import Tacotron2
from speechbrain.pretrained import HIFIGAN

# Intialize TTS (tacotron2) and Vocoder (HiFIGAN)
tacotron2 = Tacotron2.from_hparams("Path_to_Thorsten_tts_model")
hifi_gan = HIFIGAN.from_hparams("path_to_hifigan")
```

**Comment by thorstenMueller** [comment]
Hi & you're welcome 😊.
Seems that Coqui TTS has a general problem on downloading models at the moment (see: https://github.com/coqui-ai/TTS/issues/2686). Hopefully this should be fixed soon and then work for my models too.

**Comment by thorstenMueller** [comment]
According to a similar (and now closed) [issue](https://github.com/coqui-ai/TTS/issues/2693) the download server problem should be fixed. I've tested it with my DDC model and the download worked now as expected 😊. I'll close this issue, but feel to reopen it if you still encounter any download problems.
