### ISSUE TITLE
Errors for some reason.

### ISSUE THREAD

**Issue by MistakingManx** [thorstenMueller/Thorsten-Voice#62]
```
Traceback (most recent call last):
  File "D:\anaconda3\envs\TTS\lib\site-packages\trainer\trainer.py", line 1833, in fit
    self._fit()
  File "D:\anaconda3\envs\TTS\lib\site-packages\trainer\trainer.py", line 1785, in _fit
    self.train_epoch()
  File "D:\anaconda3\envs\TTS\lib\site-packages\trainer\trainer.py", line 1503, in train_epoch
    for cur_step, batch in enumerate(self.train_loader):
  File "D:\anaconda3\envs\TTS\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "D:\anaconda3\envs\TTS\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "D:\anaconda3\envs\TTS\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "D:\anaconda3\envs\TTS\lib\site-packages\torch\_utils.py", line 722, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda3\envs\TTS\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda3\envs\TTS\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "D:\AI\Testing\TTS\TTS\tts\models\vits.py", line 343, in collate_fn
    wav_padded[i, :, : wav.size(1)] = torch.FloatTensor(wav)
RuntimeError: The expanded size of the tensor (1) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [1, 44982].  Tensor sizes: [2, 44982]
```
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\Testing\TTS\train_vits.py", line 91, in <module>
    main()
  File "D:\AI\Testing\TTS\train_vits.py", line 85, in main
    trainer.fit()
  File "D:\anaconda3\envs\TTS\lib\site-packages\trainer\trainer.py", line 1860, in fit
    remove_experiment_folder(self.output_path)
  File "D:\anaconda3\envs\TTS\lib\site-packages\trainer\generic_utils.py", line 77, in remove_experiment_folder
    fs.rm(experiment_path, recursive=True)
  File "D:\anaconda3\envs\TTS\lib\site-packages\fsspec\implementations\local.py", line 185, in rm
    shutil.rmtree(p)
  File "D:\anaconda3\envs\TTS\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "D:\anaconda3\envs\TTS\lib\shutil.py", line 620, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "D:\anaconda3\envs\TTS\lib\shutil.py", line 618, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'D:/AI/Testing/TTS/vits_premier1-April-23-2024_09+49PM-dbf1a08a\\trainer_0_log.txt'
```
I lack sufficient Python understanding to solve this issue myself.

**Comment by MistakingManx** [comment]
Oh right, the file. `train_vits_win.py`.

**Comment by thorstenMueller** [comment]
I've run into the same problem with "_The process cannot access the file because it is being used by another process" while doing some tests on Windows, but i'm not sure how i solved it. But this happens when training already crashed and the process tries cleaning up the training folder.
- Did you run your command line with admin privilieges?
- Is there any file open from the training directory in explorer?

**Comment by MistakingManx** [comment]
The issue I'm having is primarily the `RuntimeError: The expanded size of the tensor (1) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [1, 44982].  Tensor sizes: [2, 44982]` issue. I don't understand what this is.

**Comment by thorstenMueller** [comment]
Sorry for late response. Anything new here or still same error?

**Comment by thorstenMueller** [comment]
I close this issue, but feel free to reopen it at any time if needed.

**Comment by MistakingManx** [comment]
Still same.
